---
title: "Module 1.2: Review materials"
output: 
  html_document:
    css: reading.css
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Review on your own, as needed

Prerequisites for this course include STA 360/601/602 (Bayesian Inference) and all its prerequisite at Duke (linear algebra, multivariable calculus, probability, inference, and regression).

Review slides are provided for linear algebra as well as some probability and inference material, including the following. Please familiarize yourself with the content of these notes if your recollection is fuzzy.

- basic properties of vectors and matrices
- linear independence, dependence, and rank of a matrix
- inversion of full-rank and less than full-rank matrices
- common distributions
- maximum likelihood estimation



## Review slides

[Basics: Vectors and matrices](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-1.html)

[Linear dependence and rank](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-2.html)

[Determinants and inverses](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-3.html)

[Random vectors and matrices](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-4.html)

[Important distributions](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-5.html)

[Maximum likelihood](https://ids-610l-s21.github.io/Course-Website/slides/1-2-review-6.html)



## Other review resources

Penn State University maintains some very nice review materials online (these are shorter in length than the slides above.)


[Matrix definitions](https://onlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra/definitions)

[Matrix arithmetic](https://onlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra/arithmetic)

[Matrix properties](https://onlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra/properties)

[Matrix inverse](https://onlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra/inverse)

[Advanced matrix properties](https://onlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra/advanced-properties)


